import * as utils from '@contentlayer/utils'

import type { DocumentTypeDef } from '../schema/index.js'

export const autogeneratedNote = `NOTE This file is auto-generated by Contentlayer`

function isEnglish(input: string) {
  // Regular expression that matches non-ASCII characters.
  const regex = /[^\x00-\x7F]/

  // If there are no foreign characters, it means it's in English.
  // We negate the test result to get the indication of English text.
  return !regex.test(input)
}

export const getDataVariableName = ({ docDef }: { docDef: DocumentTypeDef }): string => {
  if (!isEnglish(docDef.name)) {
    return docDef.name
  }

  if (docDef.isSingleton) {
    return utils.lowercaseFirstChar(utils.inflection.singularize(docDef.name))
  } else {
    return 'all' + utils.uppercaseFirstChar(utils.inflection.pluralize(docDef.name))
  }
}
